#!/bin/sh

case "$ACTION" in
        add)
                case "$DEVNAME" in
                        sd[a-z][0-9])
                                mkdir -p /mnt/usb
                                mount /dev/$DEVNAME /mnt/usb
                                echo 255 > /sys/class/leds/red:wifi/brightness
                                ;;
                esac
                ;;

        remove)
                case "$DEVNAME" in
                        sd[a-z][0-9])
                                echo 0 > /sys/class/leds/red:wifi/brightness
                                ;;
                esac
                ;;
esac
